name = "Kolmogorov"
uuid = "a24721c7-e67f-4b32-8f0b-7b8e6fb5aed9"
authors = ["Ryan Dungee <ryan.dungee@utoronto.ca>"]
version = "0.0.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
FFTW = "1"
julia = "1.6.7"
